### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by AndyMuc** [f-meloni/Logger#7]
Hello @f-meloni ,

while traversing the dependency graph of "Sourcery" I stumbled upon this project. Currently this project has no license information. A repo wide search for a copyright also yielded no results. This most probably is just an oversight? Could you please add a license so everybody can use, share and modify the code? You might want to take a look at this page for more information: https://choosealicense.com/no-permission/

Thanks in advance,
Andy

**Comment by f-meloni** [comment]
Hey @AndyMuc!
You are right, I forgot to add the licence file.
https://github.com/shibapm/Logger/pull/8 should fix it, thank you :)
